### PR TITLE
Updated main.py to show less items

### PR DESCRIPTION
**Pull request by cncastillo**
The list of items when no query is inserted is too long, changed to show just the first 5 items. I think it looks better.

### CODE REVIEW

**Comment by noam09** [comment]
Hi @cncastillo, thanks for the addition. 

The first 5 items certainly appears cleaner, but is there a way the user can be shown 5 items which are relevant specifically to him/her? Maybe sort the list of items according to past frequency of usage?

**Comment by cncastillo** [comment]
Yes, definitely that is the way to go. You could write a .log file just with the number of times each app has been used and then sort the apps accordingly.

**Comment by noam09** [comment]
@cncastillo, the [latest commit](https://github.com/noam09/ulauncher-gnome-control-center/commit/9fde6076f3c1584dad581afcad892018c877996c) introduces sorting by usage, in addition to a shorter list of initial results. 
Would you like to try it out and see if it works as planned? You should restart Ulauncher after the update so the icons get reloaded.

**Comment by cncastillo** [comment]
Yes! It works perfectly :)

**Comment by noam09** [comment]
Awesome :)
Closing then...

**Pull request closed without merging**
